name: "Baseprinter Action"
description: |
  Generate HTML/PDF previews of Baseprint document snapshot and deploy to GitHub Pages.
inputs:
  defaults-file:
    description: "Pandoc defaults file path"
    required: true
runs:
  using: 'composite'
  steps:
    - name: "Checkout source"
      uses: actions/checkout@v4
    - name: "Generate HTML/PDF previews of Baseprint document snapshot"
      uses: docker://docker.io/castedo/baseprinter:20231029
      with:
        args: >-
          baseprinter
          --defaults ${{ inputs.defaults-file }}
          --baseprint baseprint
          --outdir _site
    - name: "Upload Pages artifact"
      uses: actions/upload-pages-artifact@v2
      with:
        path: "_site/"
