name: "Baseprinter Action"
description: |
  Generate HTML/PDF previews of Baseprint document snapshot and deploy to GitHub Pages.
inputs:
  defaults-file:
    description: "Pandoc defaults file path"
    required: true
runs:
  using: 'composite'
  steps:
    - name: "Checkout source"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Prepare autobaseprint branch"
      shell: bash
      run: |
        git config user.name  "Baseprinter Action Bot"
        git config user.email "<>"
        git fetch origin autobaseprint || git branch autobaseprint
        git switch autobaseprint
        git log -1 --format=%H
        git merge --no-commit main
        git status
        rm -rf baseprint
    - name: "Generate HTML/PDF previews of Baseprint document snapshot"
      uses: docker://registry.gitlab.com/perm.pub/dock/baseprinter:20240813
      with:
        args: >-
          baseprinter
          --defaults ${{ inputs.defaults-file }}
          --baseprint baseprint
          --outdir _site
    - name: "Commit generated baseprint"
      shell: bash
      run: |
        git add baseprint
        git commit -m "generated baseprint snapshot"
        git push origin autobaseprint
    - name: "Upload Pages artifact"
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_site/"
